swagger: '2.0'
info:
  version: 1.0.0
  title: Exposing System Run Time of Stream Processor
  description: >-
    This provides information about the runtime of the stream processor.
  contact:
    name: WSO2
    url: 'http://wso2.com/analytics'
    email: architecture@wso2.org
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
schemes:
  - https
host: analytics.wso2.com
basePath: /distributed/apis
paths:
  '/runTime':
    get:
      x-wso2-curl: 'curl -k -X GET http://localhost:9090/stream-processor/runTime/{host}/{port}'
      x-wso2-request: 'GET http://localhost:9090/stream-processor/runTime/{host}/{port}'
      x-wso2-response: |-
        HTTP/1.1 200 OK Content-Type: application/json {
         "manager"
        }
      tags:
        - RunTime
      summary: Returns the runtime of the stream processor.
      description: >-
        Returns the run time given in the carbon.sh.
      operationId: getRunTime
      responses:
        '200':
          description: OK.
        '404':
          description: Not Found.
        '500':
          description: An unexpected error occured.
          schema:
            $ref: '#/definitions/ApiResponseMessage'
definitions:
  ApiResponseMessage:
    type: object
    properties:
      message:
        type: string
        description: Error message
