strategy: "org.wso2.carbon.cluster.coordinator.ZookeeperCoordinationStrategy"
rdbmsConfig:
    heartbeatInterval: 1000
    eventPollingInterval: 1000
    taskThreadCount: 1
zookeeperConfig:
    connectionString: "localhost:2181"