<node>
<label>Servers</label>
<value>0</value>
<children>
    <node>
	    <label>https://10.100.1.177:9345/esb</label>
	    <value>1</value>
	    <children>
		    <node>
			    <label>Endpoints</label>
			    <value>-2</value>
			    <children>
				    <node>
					    <label>endpoint_urn_uuid_B179169968A68CB7C8252902356101431285066263__checkCredit
					    </label>
					    <value>-2</value>
				    </node>
				    <node>
					    <label>Supplier3OrderProcessingEndpoint__placeOrder</label>
					    <value>-3</value>
				    </node>
				    <node>
					    <label>Supplier2OrderProcessingEndpoint__placeOrder</label>
					    <value>-4</value>
				    </node>
				    <node>
					    <label>Supplier1OrderProcessingEndpoint__placeOrder</label>
					    <value>-5</value>
				    </node>
			    </children>
		    </node>
		    <node>
			    <label>Proxy Services</label>
			    <value>-3</value>
			    <children>
				    <node>
					    <label>OrderApproval</label>
					    <value>-2</value>
				    </node>
				    <node>
					    <label>OrderBooking</label>
					    <value>-3</value>
				    </node>
				    <node>
					    <label>OrderFulfillment</label>
					    <value>-4</value>
				    </node>
			    </children>
		    </node>
		    <node>
			    <label>Sequences</label>
			    <value>-4</value>
			    <children>
				    <node>
					    <label>SupplierOrderProcessingSequence</label>
					    <value>-2</value>
				    </node>
			    </children>
		    </node>
	    </children>
    </node>
    <node>
	    <label>https://10.100.1.143:9444</label>
	    <value>2</value>
	    <children>
		    <node>
			    <label>Endpoints</label>
			    <value>-2</value>
		    </node>
		    <node>
			    <label>Proxy Services</label>
			    <value>-3</value>
		    </node>
		    <node>
			    <label>Sequences</label>
			    <value>-4</value>
		    </node>
		    <node>
			    <label>HelloService</label>
			    <value>1</value>
			    <children>
				    <node>
					    <label>greet</label>
					    <value>1</value>
				    </node>
			    </children>
		    </node>
		    <node>
			    <label>wso2carbon-sts</label>
			    <value>2</value>
			    <children>
				    <node>
					    <label>IssueToken</label>
					    <value>2</value>
				    </node>
			    </children>
		    </node>
		    <node>
			    <label>XKMS</label>
			    <value>3</value>
			    <children>
				    <node>
					    <label>ValidateRequest</label>
					    <value>3</value>
				    </node>
				    <node>
					    <label>RegisterRequest</label>
					    <value>4</value>
				    </node>
				    <node>
					    <label>ReissueRequest</label>
					    <value>5</value>
				    </node>
				    <node>
					    <label>LocateRequest</label>
					    <value>6</value>
				    </node>
				    <node>
					    <label>RecoverRequest</label>
					    <value>7</value>
				    </node>
				    <node>
					    <label>RevokeRequest</label>
					    <value>8</value>
				    </node>
			    </children>
		    </node>
	    </children>
    </node>
</children>
</node>
