swagger: '2.0'
info:
  description: >-
    This is the REST Micro Service for System Availability.
  version: 1.0.0
  title: Stream Processor Health Check API
  termsOfService: 'http://wso2.com/terms'
  contact:
    email: dev@wso2.org
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
basePath: /v1.0
tags:
  - name: health
    description: Everything about Stream Processor health
    externalDocs:
      description: Find out more about server health
      url: 'https://docs.wso2.com/display/SP400/Key+Concepts'
schemes:
  - http
paths:
  /health:
    get:
      x-wso2-curl: 'curl -k -X GET http://localhost:9090/health'
      x-wso2-request: 'GET http://localhost:9090/health'
      x-wso2-response: 'HTTP/1.1 200 OK Content-Type: application/json {"status":"active"}'
      tags:
        - Artifact
      summary: Fetches the status of the Stream Processor.
      description: |
        Fetches the status of the Stream Processor.
      produces:
        - application/json
      responses:
        '200':
          description: The state of the Stream Processor is successfully retrieved.
          schema:
            $ref: '#/definitions/ServerStatus'

definitions:
  ServerStatus:
    type: object
    properties:
      status:
        type: string
        description: Server runtime status

