swagger: '2.0'
info:
  version: 1.0.0
  title: Stream Processor Authentication Service
  description: This provides service to authenticate users in Stream Processor
  contact:
    name: WSO2
    url: 'http://wso2.com/smart-analytics'
    email: architecture@wso2.org
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
schemes:
  - http
  - https
host: analytics.wso2.com
basePath: /
consumes:
  - application/json
produces:
  - application/json
paths:
  /login/{appName}:
    post:
      description:
        Login Request to Stream Processor which returns user info, access and refresh token as cookies along with user name.
      consumes:
        - application/x-www-form-urlencoded
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: appName
          in: path
          description: AppName
          type: string
          required: true
        - name: username
          in: formData
          type: string
        - name: password
          in: formData
          type: string
        - name: grantType
          in: formData
          type: string
        - name: rememberMe
          in: formData
          type: boolean
          default: false
      responses:
        '200':
          description: Authorization Request Successful.
          schema:
            $ref: "#/definitions/User"
        '302':
          description: Redirection for OAuth2 authorization grant type.
          schema:
            $ref: "#/definitions/Redirection"
        '401':
          description: Invalid Authorization Header
          schema:
            $ref: "#/definitions/Error"
        '500':
          description: An unexpected error occured.
          schema:
            $ref: "#/definitions/Error"
  /login/callback/{appName}:
    get:
      description:
        Login Request callback for Authorization Code grant type which returns user info, access and refresh token as
        cookies along with user name. .
      produces:
        - application/json
      parameters:
        - name: appName
          in: path
          description: AppName
          type: string
          required: true
      responses:
        '200':
          description: Authorization Request Successful.
          schema:
            $ref: "#/definitions/User"
        '401':
          description: Invalid Authorization Header
          schema:
            $ref: "#/definitions/Error"
        '500':
          description: An unexpected error occured.
          schema:
            $ref: "#/definitions/Error"
  /logout/{appName}:
    post:
      description:
        Logout Request to Stream Processor which clears cookies
      parameters:
        - name: appName
          in: path
          description: AppName
          type: string
          required: true
      responses:
        '200':
          description: Authorization Request Successful.
        '500':
          description: An unexpected error occured.
          schema:
            $ref: "#/definitions/Error"
  /userstore/groups:
    get:
      description:
        Get all the groups in the user store.
      produces:
        - application/json
      responses:
        '200':
          description: Get all the groups in the user store Request Successful.
          schema:
            $ref: "#/definitions/GroupsList"
        '401':
          description: Invalid Authorization Header
          schema:
            $ref: "#/definitions/Error"
        '500':
          description: An unexpected error occured.
          schema:
            $ref: "#/definitions/Error"
  /userstore/users/{name}/groups:
    get:
      description:
        Get user's groups from the user store.
      produces:
        - application/json
      parameters:
        - in: path
          name: name
          schema:
           type: string
          required: true
          description: ID of the user to get
      responses:
        '200':
          description: Get my groups from the user store Request Successful.
          schema:
            $ref: "#/definitions/GroupsList"
        '401':
          description: Invalid Authorization Header
          schema:
            $ref: "#/definitions/Error"
        '500':
          description: An unexpected error occured.
          schema:
            $ref: "#/definitions/Error"
definitions:
  User:
    type: object
    properties:
      id:
        type: string
      isTokenValid:
        type: boolean
      validityPeriod:
        type: integer
      partialAccessToken:
        type: string
      partialRefreshToken:
        type: string
      authUser:
        type: string
  Redirection:
    type: object
    properties:
      clientId:
        type: string
      redirectUrl:
        type: string
      callbackUrl:
        type: string
  GroupsList:
    type: array
    items:
      $ref: '#/definitions/Group'
  Group:
    type: object
    properties:
      id:
        type: string
      display:
        type: string
  Error:
    type: object
    properties:
      message:
        type: string
        description: Error message