
CREATE TABLE IF NOT EXISTS AM_USAGE_UPLOADED_FILES (
  FILE_NAME varchar(255) NOT NULL,
  FILE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FILE_PROCESSED tinyint(1) DEFAULT 0,
  FILE_CONTENT MEDIUMBLOB DEFAULT NULL,
  PRIMARY KEY (FILE_NAME, FILE_TIMESTAMP)
);